// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// get_altitudes_for_azimuth_cpp
NumericMatrix get_altitudes_for_azimuth_cpp(NumericMatrix& dem, double azimuth, double gridConvergence, double resolution);
RcppExport SEXP _sunlightRCPP_get_altitudes_for_azimuth_cpp(SEXP demSEXP, SEXP azimuthSEXP, SEXP gridConvergenceSEXP, SEXP resolutionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix& >::type dem(demSEXP);
    Rcpp::traits::input_parameter< double >::type azimuth(azimuthSEXP);
    Rcpp::traits::input_parameter< double >::type gridConvergence(gridConvergenceSEXP);
    Rcpp::traits::input_parameter< double >::type resolution(resolutionSEXP);
    rcpp_result_gen = Rcpp::wrap(get_altitudes_for_azimuth_cpp(dem, azimuth, gridConvergence, resolution));
    return rcpp_result_gen;
END_RCPP
}
// get_min_altitude_for_azimuth_cpp
double get_min_altitude_for_azimuth_cpp(NumericMatrix& dem, int col, int row, double maxElev, double dx, double dy, double dxy);
RcppExport SEXP _sunlightRCPP_get_min_altitude_for_azimuth_cpp(SEXP demSEXP, SEXP colSEXP, SEXP rowSEXP, SEXP maxElevSEXP, SEXP dxSEXP, SEXP dySEXP, SEXP dxySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix& >::type dem(demSEXP);
    Rcpp::traits::input_parameter< int >::type col(colSEXP);
    Rcpp::traits::input_parameter< int >::type row(rowSEXP);
    Rcpp::traits::input_parameter< double >::type maxElev(maxElevSEXP);
    Rcpp::traits::input_parameter< double >::type dx(dxSEXP);
    Rcpp::traits::input_parameter< double >::type dy(dySEXP);
    Rcpp::traits::input_parameter< double >::type dxy(dxySEXP);
    rcpp_result_gen = Rcpp::wrap(get_min_altitude_for_azimuth_cpp(dem, col, row, maxElev, dx, dy, dxy));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_sunlightRCPP_get_altitudes_for_azimuth_cpp", (DL_FUNC) &_sunlightRCPP_get_altitudes_for_azimuth_cpp, 4},
    {"_sunlightRCPP_get_min_altitude_for_azimuth_cpp", (DL_FUNC) &_sunlightRCPP_get_min_altitude_for_azimuth_cpp, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_sunlightRCPP(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
